### ISSUE TITLE
naming; change if, consequent, alternate

### ISSUE THREAD

**Issue by wanderer** [drom/wast-spec#15]
Currently we have

```
{
  kind: 'if',
  test: <expr>,
  consequent: <expr>,
  alternate: <expr> | null
}
```

But most WASM documentation refers to `then` and `else`
so what about ?

```
{
  kind: 'if',
  test: <expr>,
  then: <expr>,
  else: <expr> | null
}
```

**Comment by drom** [comment]
I was blindly coping these keys from JS AST, but I like `then`, `else` more. Please change the spec.

**Comment by wanderer** [comment]
ok in pr #17

**Comment by drom** [comment]
@wanderer we have one more place with`consequent` and `alternate` --> `select`
What would you do there?

**Comment by wanderer** [comment]
hmm so select works a bit differently I think.  for select I would just use something like `left`, `right`, `test`. Since both the `left` and `right` get run and `test` decides which to return.

**Comment by wanderer** [comment]
^ but i'm not sure, wouldn't hurt to write a test to see how it behaves

**Comment by drom** [comment]
@wanderer can we call them `then, else, test` ? or it is confusing?

**Comment by wanderer** [comment]
@drom yep! did experiment both don't run right away so `then`, `else`, `test` are the right names

**Comment by drom** [comment]
I have fixed the parser

**Comment by wanderer** [comment]
updated spec in pr #18
