### ISSUE TITLE
Items in param

### ISSUE THREAD

**Issue by wanderer** [drom/wast-spec#9]
so item here should be a type

```
{
  kind: 'param',
  items: [ <item> ]
}
```

would this make sense?

```
{
  kind: 'param',
  items: [ <type> ]
}
```

**Comment by drom** [comment]
To my knowledge `param` in WebAssembly present in several forms:

`(param)` -- empty form:
`(param $x i32)` -- id and type:
`(param i32)` -- single type only
`(param i32 i32)` -- multiple types

We have to accommodate all of them.

**Comment by wanderer** [comment]
ah yep your right
